name: myenv
channels:
  - conda-forge
  - anaconda 
dependencies:
  - python=3.9.13
  - flask=2.3.2
  - scipy=1.11.1
  - scikit-learn=1.3.0
  - gunicorn=21.2.0
  - numpy
  - pandas
  - tensorflow
  - pillow